security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        database:
            entity:
                class: App\Entity\User
                property: username
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            anonymous: true
            pattern: ^/
            stateless: true
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    
    role_hierarchy:
        ROLE_MUTED: []
        ROLE_USER: []
        ROLE_COMMENTATOR: [ROLE_USER]
        ROLE_MODERATOR: [ROLE_COMMENTATOR]
        ROLE_ADMINISTRATOR: [ROLE_MODERATOR]
        ROLE_SUPER_ADMINISTRATOR: [ROLE_ADMINISTRATOR]
    
    access_control:
        - { path: '^/admin', roles: ROLE_ADMINISTRATOR }
        - { path: '^/profile', roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/account', roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/', roles: IS_AUTHENTICATED_ANONYMOUSLY }
