App\Entity\PostComment:
    
    properties:
        author:
            subresource:
                resourceClass: App\Entity\User
                collection: false
    
    itemOperations:
        get:
            method: GET
            access_control: is_granted('VIEW', object)
            normalization_context:
                groups: ['get']
        put:
            method: PUT
            access_control: is_granted('EDIT', object)
            denormalization_context:
                groups: ['put']
    
    collectionOperations:
        get:
            method: GET
            normalization_context:
                groups: ['get-post-with-comments']
        post:
            method: POST
            access_control: is_granted('CREATE', object)
            denormalization_context:
                groups: ['post']
            normalization_context:
                groups: ['get']
#        api_posts_comments_get_subresource:
#            method: GET
#            normalization_context:
#                groups: ['get-post-with-comments']