App\Entity\Post:
    
    properties:
        category:
            subresource:
                resourceClass: App\Entity\PostCategory
        comments:
            subresource:
                resourceClass: App\Entity\PostComment
        likedBy:
            subresource:
                resourceClass: App\Entity\User
        tags:
            subresource:
                resourceClass: App\Entity\Tag
    
    itemOperations:
        get:
            method: GET
            access_control: is_granted('VIEW', object)
            normalization_context:
                groups: ['get']
        put:
            method: PUT
            access_control: is_granted('EDIT', object)
            denormalization_context:
                groups: ['put']
    
    collectionOperations:
        get:
            method: GET
            normalization_context:
                groups: ['get-post-with-comments']
        post:
            method: POST
            access_control: is_granted('CREATE', object)
            denormalization_context:
                groups: ['post']
    