App\Entity\User:
        
    itemOperations:
        get:
            method: GET
            access_control: is_granted('VIEW', object)
            normalization_context:
                groups: ['get']
        put:
            method: PUT
            access_control: is_granted('EDIT', object)
            denormalization_context:
                groups: ['put']
                
    collectionOperations:
        post:
            method: POST
            access_control: is_granted('CREATE', object)
            denormalization_context:
                groups: ['post']
            normalization_context:
                groups: ['get']