parameters:
    key: '%env(JWT_KEY)%'
    adminMailFrom: '%env(MAILER_FROM)%'
    adminMailTo: '%env(MAILER_TO)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    App\Mail\Mailer:
        arguments:
            $adminMailFrom: '%adminMailFrom%'
            $adminMailTo: '%adminMailTo%'
    
#    App\EntityListener\EntityListener:
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }
#            - { name: doctrine.event_listener, event: preUpdate }
#            - { name: doctrine.event_listener, event: postLoad }