parameters:
    key: '%env(JWT_KEY)%'
    adminMailFrom: '%env(MAILER_FROM)%'
    adminMailTo: '%env(MAILER_TO)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $projectDir: '%kernel.project_dir%'
            $imageDir: '%kernel.project_dir%/public/images/uploaded/'
            $webPath: '%env(APP_URL)%'
    
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    App\Mail\Mailer:
        arguments:
            $adminMailFrom: '%adminMailFrom%'
            $adminMailTo: '%adminMailTo%'